DROP TABLE IF EXISTS CITY;  
CREATE TABLE CITY (  
City_code INT AUTO_INCREMENT  PRIMARY KEY,  
city_name VARCHAR(50) NOT NULL,  
city_pincode INT(8) NOT NULL  
);
DROP TABLE IF EXISTS Comments;  
CREATE TABLE Comments (  
postId INT AUTO_INCREMENT  PRIMARY KEY,  
id INT(8) NOT NULL,  
name VARCHAR(50) NOT NULL,
email VARCHAR(50) NOT NULL,
body VARCHAR(50) NOT NULL
);
DROP TABLE IF EXISTS Users;  
CREATE TABLE Users (  
userId INT AUTO_INCREMENT  PRIMARY KEY,  
id INT(8) NOT NULL,  
userName VARCHAR(50) NOT NULL,
email VARCHAR(50) NOT NULL,
address VARCHAR(50) NOT NULL,
phone VARCHAR(50) NOT NULL
);
DROP TABLE IF EXISTS Posts;  
CREATE TABLE Posts (  
id INT AUTO_INCREMENT  PRIMARY KEY,  
title VARCHAR(50) NOT NULL,
userId VARCHAR(50) NOT NULL,
body VARCHAR(50) NOT NULL
);